[project]
name = "chat-bot"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=0.28.0",
    "python-dotenv>=1.0",
    "requests>=2.28",
    "ruff>=0.14.6",
    "streamlit>=1.25",
]
